package generation

// Response holds answers generated by LLMs with citations context.
type Response struct {
	Answer     string   `json:"answer"`
	Confidence float64  `json:"confidence"`
	Citations  []string `json:"citations,omitempty"`
}
